# Promessas

Refatoramos a função para trabalhar de forma assincrona, pois não sabemos qual é o tamanho dos arquivos que vamos receber e se deixarmos o código sincrono pode dar algum problema. Vamos começar usando o .then() e .catch():

    import fs from 'fs';
    import chalk from 'chalk';

    function trataErro(erro) {
        throw new Error(chalk.red(erro.code, 'não há arquivo no diretório'));
    }

    function pegaArquivo(caminhoDoArquivo) {

        const encoding = 'utf-8';

        fs.promises.readFile(caminhoDoArquivo, encoding)
            .then((texto) => console.log(chalk.green(texto)))
            .catch(trataErro)
    }

Como a função .catch() recebe uma função callback como parâmetro podemos simplesmente fazer dessa forma:

    .catch(trataErro)

Pois de baixo dos panos a função catch() está passando o parâmetro erro para a função trataErro.

O .then() também recebe uma função callback, mas através do parâmetro pegamos o return que no nosso caso e o texto e tratamos ele da forma que charmos melhor.
