# Refatorando o manipulador de erros

Utilizamos conceitos de POO em nossa aplicação para tratar de uma melhor forma os erros. Primeiro criamos uma pasta chamada erros dentro de src. Dentro dessa pasta criamos três arquivos:

ErroBase.js:

    class ErroBase extends Error {
        constructor(mensagem = "Erro interno do servidor", status = 500) {
            super();
            this.message = mensagem;
            this.status = status;
        }

        enviarResposta(res) {
            res.status(this.status).send({
                mensagem: this.message, 
                status: this.status
            });
        }
    }

    export default ErroBase;

ErroValidacao.js :

    import RequisicaoIncorreta from "./RequisicaoIncorreta.js";

    class ErroValidacao extends RequisicaoIncorreta {
        constructor(erro) {

            const mensagensErro = Object.values(erro.errors).map(erro => erro.message).join("; ");

            super(`Os seguintes erros foram encontrados: ${mensagensErro}`);
        }
    }

    export default ErroValidacao;

RequisicaoIncorreta.js:

    import ErroBase from "./ErroBase.js";

    class RequisicaoIncorreta extends ErroBase {
        constructor (mensagem = "Um ou mais dados fornecidos estão incorretos") {
            super(mensagem, 400);
        }
    }

    export default RequisicaoIncorreta;

Como podemos ver criamos classes separadas para cada erro e dessa forma temos um código mais organizado.

